# ______ _                         _____ _        _               _____ _
# | ___ \ |                       /  ___| |      | |             /  ___(_)
# | |_/ / | __ _ _   _  ___ _ __  \ `--.| |_ __ _| |_ _   _ ___  \ `--. _  __ _ _ __  ___
# |  __/| |/ _` | | | |/ _ \ '__|  `--. \ __/ _` | __| | | / __|  `--. \ |/ _` | '_ \/ __|
# | |   | | (_| | |_| |  __/ |    /\__/ / || (_| | |_| |_| \__ \ /\__/ / | (_| | | | \__ \
# \_|   |_|\__,_|\__, |\___|_|    \____/ \__\__,_|\__|\__,_|___/ \____/|_|\__, |_| |_|___/
#                 __/ |                                                    __/ |
#                |___/                                                    |___/
#    By: MartenM
#
#----------------------------------------------------------------------------------------------
# PlaceHolders
#   %name%      - The players name
#   %world%     - The world a player is in.
#   %x% %y% %z% - The X Y or Z coord of a player.
#
#   If Essentials plugin is present:
#   %balance%   - The amount of money a player has
#
#   If the PlaceHolderAPI plugin is present:
#   All the placeholderapi placeholders you have installed.
#   NOTE: Only works for ONLINE players (so afk players will work too)
#-----------------------------------------------------------------------------------------------
#
clickable signs: true
#
format:
#
# Format date
  date: "dd:MM:yyyy"
#
# The format for when someone is online.
  online:
    - "x-&a^&r-x"
    - "%player%"
    - "&aOnline"
    - "x-&av&r-x"
#
# The format used when someone is offline
  offline:
    - "x-&c^&r-x"
    - "%player%"
    - "&c%since%"
    - "x-&cv&r-x"
#
# The format used when someone is afk
  afk:
    - "x-&1^&r-x"
    - "%player%"
    - "&1AFK"
    - "x-&1v&r-x"
#
# The format shown when a sign is clicked
  click online:
    - ""
    - "&8&l────────────────────────┤"
    - "    &6%player%"
    - ""
    - "&ePosition: &7%world% %x% %y% %z%"
    - "&eThis player is currently &aonline!"
    - "&8&l────────────────────────┤"
  click offline:
    - ""
    - "&8&l────────────────────────┤"
    - "    &6%player%"
    - ""
    - "&eThis player is currently &coffline!"
    - "&8&l────────────────────────┤"
  click afk:
    - ""
    - "&8&l────────────────────────┤"
    - "    &6%player%"
    - ""
    - "&eThis player is currently &1AFK!"
    - "&8&l────────────────────────┤"
#
#
messages:
  no permission: "&cNot enough permissions."
